apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: queue
  name: queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue
  strategy: {}
  template:
    metadata:
      labels:
        app: queue
    spec:
      containers:
      - image: richardchesterwood/k8s-fleetman-queue:release1
        name: k8s-fleetman-queue
        resources: {}
status: {}
