apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: queue
  name: queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue
  template:
    metadata:
      labels:
        app: queue
    spec:
      containers:
      - image: richardchesterwood/k8s-fleetman-queue:release1
        name: k8s-fleetman-queue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postion-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postion-simulator
  template:
    metadata:
      labels:
        app: postion-simulator
    spec:
      containers:
      - image: richardchesterwood/k8s-fleetman-position-simulator:release1
        name: webapp
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: production-microservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: position-tracker
  template:
    metadata:
      labels:
        app: position-tracker
    spec:
      containers:
      - image: richardchesterwood/k8s-fleetman-position-tracker:release1
        name: position-tracker
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: production-microservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - image: richardchesterwood/k8s-fleetman-api-gateway:release1
        name: api-gateway
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: production-microservice