apiVersion: v1
kind: Service
metadata:
  labels:
    app: queue
  name: fleetman-queue
spec:
  ports:
    - name: http
      port: 8161
      nodePort: 30010
    - name: endpoint
      port: 61616
  selector:
    app: queue
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: position-tracker
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: position-tracker
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-svc
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: api-gateway
  type: ClusterIP