apiVersion: v1
kind: Service
metadata:
  labels:
    app: queue
  name: fleetman-queue
spec:
  ports:
    - name: http
      port: 8161
      nodePort: 30010
    - name: endpoint
      port: 61616
  selector:
    app: queue
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  ports:
  - port: 80
    nodePort: 30080
  selector:
    app: postion-simulator
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: position-tracker
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: position-tracker
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: api-gateway
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-svc
spec:
  ports:
    - name: http
      port: 80
      nodePort: 30081
  selector:
    app: webapp
  type: NodePort